language: java8
jdk:
  - oraclejdk8
script: mvn verify

deploy:
  provider: releases
  api_key:  d0a61930e13a912f69b10e5c804c67c81fd8236
  file: target/*.jar
  skip_cleanup: true
  on:
    tags: false
