language: java8
jdk:
  - oraclejdk8
script: mvn verify

deploy:
  provider: releases
  api_key:  ad91fd176f75f1182070e26b936614dd9eda926e
  file: target/*.jar
  skip_cleanup: true
  on:
    tags: true
